### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by lneugebauer** [eibiflo/cf_cookiemanager#1]
It is currently unclear under which license the code was released. In the readme the `MIT` license is mentioned. In the composer.json `GPL-2.0-or-later`.

Please add a `LICENSE.txt` for clarification.

**Comment by eibiflo** [comment]
Because of the Typo3 General Public License, the MIT license is not an option as far as I know.
But I forgot, so I followed suit.

Thanks for the hint!

Best wishes
