### ISSUE TITLE
"updateScan" not in Repository

### ISSUE THREAD

**Issue by jacques2017** [eibiflo/cf_cookiemanager#19]
Hi,
thanks for the great extension. In version 1.4.1 you have removed the "updateScan" method from the repository. This leads to a 503 error message when clicking on the "start a new scan" button:
'The method "updateScan" is not supported by the repository'
In my case, I simply copied the method back into the repository. The backend of the extension can now be used again.
I use TYPO3 11.5.32 with version 1.4.1 

Greetings
Jacques

**Comment by eibiflo** [comment]
Hei @jacques2017,
Thank for the hint!
