### ISSUE TITLE
Need help - deactivate Cookiemanager for one subpage

### ISSUE THREAD

**Issue by jacques2017** [eibiflo/cf_cookiemanager#20]
Hi,
is it possible to deactivate the modal for a page like the data protection or imprint?

**Comment by eibiflo** [comment]
I have already considered this problem; it's not user-friendly.

Currently, the feature to hide the modal does not exist yet.

But what you can already do is to completely remove the cookie manager via Typoscript from the Site.

To do this, you can simply create an extension Typoscript on the page and write the following line:
`page.99999999 >`

This is related to the Registration in https://github.com/eibiflo/cf_cookiemanager/blob/main/Configuration/TypoScript/setup.typoscript#L61

**Comment by jacques2017** [comment]
Thanks, that works.

**Comment by eibiflo** [comment]
Closed with #27
