### ISSUE TITLE
Possibility to show list of cookies with description in frontend

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#24]
We have the requirement to show a list of all cookies on the data protection page. Do you deliver a plugin for that function? Or is there any simple solution for that?

**Comment by eibiflo** [comment]
I believe it would be easy to use the repository and render the table in the frontend with Fluid.

Since I think this could be needed by many, I would implement it directly into the extension as a Frontend Plugin, so you can insert it on any Page.

**Comment by ChristianOsswald** [comment]
Yeah, would be really nice

**Comment by eibiflo** [comment]
I've integrated a frontend plugin that enables listing.

If you don't like the layout, you can easily override it in Fluid, as the controller delivers all relevant data in the correct language.

I hope this meets your expectations; otherwise, please provide feedback.
