### ISSUE TITLE
Preview Image for External Media

### ISSUE THREAD

**Issue by stillerfritz** [eibiflo/cf_cookiemanager#28]
It would be nice to show a  preview image instead of the black background until the user has given consent to Youtube, Vimeo etc.

**Comment by eibiflo** [comment]
Hey @stillerfritz , this topic is very interesting.

For Vimeo and YouTube, you can use the Thumbnail API; more on this here: https://docs.typo3.org/p/codingfreaks/cf-cookiemanager/main/en-us/Configuration/CookieServices/Index.html#advanced-iframe-configuration

I have already integrated a web service that processes thumbnails and makes screenshots of URLs. (Iframe Preview) 
However, it is not yet public. If you are interested, you could be one of the beta testers. The service is not stable yet.
PM Me on the Typo3 Slack if you are interested.

**Comment by stillerfritz** [comment]
thank you. I must have overlooked that.
the script for vimeo preview is exactly what we were looking for
