### ISSUE TITLE
Dashboard Widget Accept Types

### ISSUE THREAD

**Issue by stillerfritz** [eibiflo/cf_cookiemanager#29]
The integration of the cf_cookiemanager typo3 dashboard widget "accept types" throws an error.
`
Uncaught TYPO3 Exception: #1257246929: Tried resolving a template file for controller action "Standard->widget/ChartWidget" in format ".html", but none of the paths contained the expected template file (Standard/Widget/ChartWidget.html). No paths configured. | TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException thrown in file /html/typo3-composer/vendor/typo3fluid/fluid/src/View/TemplatePaths.php in line 595. Requested URL: https://xxx.de/typo3/ajax/dashboard/widget/content?token=--AnonymizedToken--&widget=consentTrackingDonutAcceptTypes
`
typo3 v11.latest

**Comment by eibiflo** [comment]
Hey, thank you, I will check it out why it happens on the V11. 

If it's possible for you, I would recommend switching to T12 as the stable version for the cookie manager will be released this year for TYPO3 V12 and V13 with some important Bugfixes.
Temporarily, if you are interested in the data, you can also query it directly from the database and load it into an Excel spreadsheet to create a chart.

Currently, the extension is in an open beta, in which the latest version would already have this fixed, but not ready for V11.

**Comment by stillerfritz** [comment]
I can confirmed it works fine with TYPO3 V12 as we have used your extension on a new client system as well. however, we won't be able to upgrade the other v11 installation this year as it would be too costly for the benefits that this would bring. we will rather switch off the dashboard widget. 
cheers
