### ISSUE TITLE
console.log on every page

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#31]
https://github.com/eibiflo/cf_cookiemanager/blame/6793b008765a10bb8d68eff04557eab272599ac6/Resources/Public/JavaScript/thirdparty/consent.js#L2444

I looked into the linked Repo but couldn't find the file. Maybe newer versions fixed this? Or could you else just delete this line?

Thanks for all your effort.

**Comment by eibiflo** [comment]
Hey, I've now removed the line, so if a 'console.log("Header");' is still output, it comes from the Google Tag Manager service API.
I have also removed it from the 'opt_in_code' field, but you would need to remove this manually if you are using the preconfigured service from the one click installer in the T3 backend.

**Comment by eibiflo** [comment]
Released with [1.6.1](https://github.com/eibiflo/cf_cookiemanager/releases/tag/v1.6.1)
