### ISSUE TITLE
Provider DSGVO could be target=_blank?

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#32]
Hi again,

I would recommend to set all external URLs with target=_blank per default. Would you agree?
![image](https://github.com/eibiflo/cf_cookiemanager/assets/147737053/4177a1ec-6082-46a4-919d-177bd14dbf5f)

Kind regards
Christian

**Comment by eibiflo** [comment]
Yes, of course, that makes sense. I've just implemented it and it will go live with the next version.

Please note that the import is only performed with new installations, which means you would need to re-import the services.

**Comment by eibiflo** [comment]
It is definitely possible to modify and integrate the data. This can be done either by replicating the API calls or by adapting the offline datasets to your needs. I would recommend the latter.

Offline datasets have been imported here; I could further expand these to simplify the process.

https://github.com/eibiflo/cf_cookiemanager/issues/14

Does this meet your requirements, or do you envision the workflow differently?

**Comment by ChristianOsswald** [comment]
Yes, thank you very much.
