### ISSUE TITLE
Backend internal link wrong in frontend

### ISSUE THREAD

**Issue by kveldscholten** [eibiflo/cf_cookiemanager#5]
Hi,

If select a internal page at Dsgvo Link in the backend Cookies settings, it does not become a link in the frontend but writes directly t3://page?uid=20 and target _blank although nothing was selected at Target.
`<a target="_blank" href="t3://page?uid=20">Provider</a>`

It would be more flexible to insert the target only when selected.

**Comment by eibiflo** [comment]
Thank you, @kveldscholten , for submitting the issue. I overlooked that.

It's fixed with this commit: https://github.com/eibiflo/cf_cookiemanager/commit/de842f7b675584ba28dbe98c1d8c69047c7f0e42
I'll release it once I've tested the other small changes in the Update Wizard.
