### ISSUE TITLE
Removing default CSS/JS

### ISSUE THREAD

**Issue by srchild** [eibiflo/cf_cookiemanager#51]
config.removeDefaultCss doesn't stop the loading of the css file because it isn't configured as _CSS_DEFAULT_STYLE

Setting page.includeCSS.cookieconsent =  or page.includeCSS.cookieconsent > in my sitepackage also doesn't stop it.

I want to stop it loading of your file so that I can copy the css into my main css file and reduce the number of elements in a page load.

Is there a way to do it?

Perhaps your extension typoscript could be adjusted to designate it as _CSS_DEFAULT_STYLE so that it can be removed by config.removeDefaultCss

And, same question about the js - can I stop the loading of that so that I can include it in another file which is already being loaded?

Thanks

**Comment by eibiflo** [comment]
Hello @srchild,

Thank you for the info! It seems like it’s incorrectly registered as a plugin. I’m using the site package approach and will look into implementing it correctly in the next release.

For now,
page.includeCSS.cookieconsent >

should work. Could it be that your TypoScript order is incorrect?
[Themes Doc](https://docs.typo3.org/p/codingfreaks/cf-cookiemanager/main/en-us/Developer/Themes/Index.html)

Regarding the JavaScript, does #20 address your issue, or do you want to include the JS code in a Build System?

The JavaScript can be included via an external file or inline in the HTML DOM, but it’s generated dynamically. Therefore, it cannot be included directly in your own JavaScript code.
(See: [CookieFrontendController.php, Line 112](https://github.com/eibiflo/cf_cookiemanager/blob/main/Classes/Controller/CookieFrontendController.php#L112))
This is not the best solution, we are currently discussing it in the Slack channel to ensure that the templates also receive Fluid support. This is already an known Issue.

**Comment by srchild** [comment]
Thanks for the quick response.

page.includeCSS.cookieconsent > does now work for me, after I reordered my included TS to place cf_cookiemanager above my site package, so thanks for that tip.

#20 looks interesting, I hadn't thought of that but might implement it. Currently I'm focusing more on improving page load speed, for example loading only one css file instead of lots of small files (and same interest for js, but clearly that won't work for dynamically generated js)

Thanks

**Comment by eibiflo** [comment]
No Problem, fine.

I'll take a closer look at _CSS_DEFAULT_STYLE, as that would make more sense than the current code, i think. 

If you're already working on optimizing the page load speed, I'm open to suggestions.
You probably want to minify everything into one file, or do you have another plan?

For example, you could minify [this section](https://github.com/eibiflo/cf_cookiemanager/blob/main/Configuration/TypoScript/setup.typoscript#L95C12-L96C101), but keep in mind that the configuration is dynamically delivered as JSON and processed by the controller.

Is there anything else I could optimize, regardless of usage, to ensure all users of the extension benefit right away?

**Comment by eibiflo** [comment]
Hei  @srchild 

if I understand correctly, _CSS_DEFAULT_STYLE is only intended for "short" CSS and not for .css files. This makes little sense in this case since an SCSS compiler is needed beforehand, which means a default theme cannot be stored in TypoScript and the PAGE type must be used to apply the themes.

Do you agree?

**Comment by srchild** [comment]
using page.includeCSS.cookieconsent > is working for me and good enough for me. 

_CSS_DEFAULT_STYLE is an alternative mechanism for removing css files, and can be used at the level of the configuration of an individual extension or for the whole installation using config.removeDefaultCss

The underlying question is what problem does it add if the css is copied into another css file - e.g. I will need to update my merged file if you ship different css in a future upgrade.

The other question is what benefit do you offer by dynamically generating css and js.

Do they only change on upgrades? In which case they could be static.

Do they change on every page load, or stay the same on page reloads of the same page but vary on other pages? 

It might be that on some pages you can offer smaller files, while other pages need extra code. But those small variations in size of the files give minimal benefit to page load time. Static files which can be cached by the browser and reused on every page, and which can also be pre-loaded on page requests, and can be merged with other files to reduce the number of asset transfers initiated, offer significant benefits (with some disadvantage if the required css changes on upgrades to the extension).

**Comment by srchild** [comment]
I'm not using SCSS but I can see from what you say that perhaps it is something to consider. I'll put looking into it on my todo list :)

Thanks

**Comment by eibiflo** [comment]
You don't have any more issues with your setup now, do you? 

Then I would close the issue for now. If further additions on the topic arise, we can define what we need and and how to prepare it well for everyone either in a discussion or on the T3-Slack?
