### ISSUE TITLE
CookieFrontendRepository API queries

### ISSUE THREAD

**Issue by kveldscholten** [eibiflo/cf_cookiemanager#6]
Can you extend queries for API insert so that modal layout, transition, position etc. can also be set by the API.

[CookieFrontendRepository.php](https://github.com/eibiflo/cf_cookiemanager/blob/main/Classes/Domain/Repository/CookieFrontendRepository.php#L155)
```
$frontendModel->setLayoutConsentModal("cloud");
$frontendModel->setTransitionConsentModal("slide");
$frontendModel->setPositionConsentModal("bottom center");

$frontendModel->setLayoutSettings("box");
$frontendModel->setTransitionSettings("slide");
```

**Comment by eibiflo** [comment]
Those are actually just the default values, so why would someone want to set them in the API?

The API is currently managed by me and is exclusively used for the preconfiguration of services, frontend and cookies, To save time during setup.

**Comment by kveldscholten** [comment]
We use the cookie-banner in our own template EXT so we want to set as much as possible through the EXT without configuring anything manually.
