### ISSUE TITLE
Function always returns true 

### ISSUE THREAD

**Issue by camCut** [eibiflo/cf_cookiemanager#8]
https://github.com/eibiflo/cf_cookiemanager/blob/ba1ffe7ac19c88232f18e9f248da08a26d1efa22/Classes/Updates/StaticDataUpdateWizard.php#L194

the second return should be false am i right?

**Comment by eibiflo** [comment]
That's true, but I wasn't sure whether the update True/False should be determined by the API so I still have to think of a solution. Feel free to join my extension's Typo3 Slack (in the readme) if you want to help with brainstorming.
