### ISSUE TITLE
SEO downrank in PageSpeed for button code

### ISSUE THREAD

**Issue by srchild** [eibiflo/cf_cookiemanager#9]
Resources/Private/Templates/CookieFrontend/List.html

Line 14 (the button code) doesn't have an href nor a title, and for these reasons gets a low score in PageSpeed

Adding just the following to the tag fixes it

 href="#" title="cookie consent"

**Comment by eibiflo** [comment]
@srchild Fixed with commit #[243](https://github.com/eibiflo/cf_cookiemanager/commit/75e186092b9a6644a0272aef97950faae35925eb)

Feel free to join the extension's Typo3 Slack (in the readme) if you want to help with brainstorming for more Features
